export const AUTH_USERS_COLLECTION_NAME = process.env.MONGODB_AUTH_USERS_COLLECTION ?? `users`;
export const AUTH_ACCOUNTS_COLLECTION_NAME = process.env.MONGODB_AUTH_ACCOUNTS_COLLECTION ?? `accounts`;
export const AUTH_SESSIONS_COLLECTION_NAME = process.env.MONGODB_AUTH_SESSIONS_COLLECTION ?? `sessions`;
export const AUTH_VERIFICATION_TOKENS_COLLECTION_NAME
    = process.env.MONGODB_AUTH_VERIFICATION_TOKENS_COLLECTION ?? `verificationTokens`;

export const GAME_HISTORY_COLLECTION_NAME = process.env.MONGODB_GAME_HISTORY_COLLECTION ?? `gameHistory`;
export const METRICS_COLLECTION_NAME = process.env.MONGODB_METRICS_COLLECTION ?? `metrics`;
export const SANDBOX_POSITIONS_COLLECTION_NAME = process.env.MONGODB_SANDBOX_POSITIONS_COLLECTION ?? `sandboxPositions`;
export const ACCOUNT_BOTS_COLLECTION_NAME = process.env.MONGODB_ACCOUNT_BOTS_COLLECTION ?? `accountBots`;
export const SERVER_SETTINGS_COLLECTION_NAME = `serverSettings`;
export const DATABASE_MIGRATIONS_COLLECTION_NAME
    = process.env.MONGODB_MIGRATIONS_COLLECTION ?? `databaseMigrations`;
